attendance:
  student_id: student_id
  date: date
  present: present
assessments:
  student_id: student_id
  assessment_name: assessment_name
  score: score
fees:
  student_id: student_id
  amount_due: amount_due
  amount_paid: amount_paid
  due_date: due_date
